SELECT
    A.TITLE, -- 게시글 제목
    A.BOARD_ID, -- 게시글 ID
    B.REPLY_ID, -- 댓글 ID
    B.WRITER_ID,-- 댓글 작성자 ID
    B.CONTENTS,  -- 댓글 내용
    TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID
AND TO_CHAR(A.CREATED_DATE, 'YYYYMM') = '202210'
ORDER BY B.CREATED_DATE , A.TITLE